drop PROCEDURE CLR_AGV_RECEIPT
drop ASSEMBLY CLR_AGV_RECEIPT

ALTER DATABASE Vendor_WCS SET TRUSTWORTHY ON
CREATE ASSEMBLY CLR_AGV_RECEIPT
FROM 'D:\AGVCLR\CLR_AGV_RECEIPT\CLR_AGV_RECEIPT\CLR_AGV_RECEIPT\bin\Debug\CLR_AGV_RECEIPT.dll'
WITH PERMISSION_SET=UNSAFE;
GO

CREATE PROCEDURE [dbo].[CLR_AGV_RECEIPT] 
(@mod nvarchar(20),@whid nvarchar(10),@storerkey nvarchar(50),@POKEY nvarchar(50),@ok int OUTPUT 
) 
WITH EXECUTE AS CALLER 
AS 
EXTERNAL NAME [CLR_AGV_RECEIPT].[StoredProcedures].CLR_AGV_RECEIPT
GO

--4927092510

DECLARE @aaa int
EXEC	[dbo].[CLR_AGV_RECEIPT] 'CLR_AGV_RECEIPT','ESLITE','ESLITE','receipt001' ,@aaa
select @aaa


--select * from int_api_log

--FNFG00000
--2000000005003

--select * from t_item_master
